# Generated by Django 4.2 on 2025-12-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=100)),
                ('nombre_equipo', models.TextField()),
                ('codigo_interno', models.CharField(blank=True, max_length=40, null=True)),
                ('codigo_ips', models.CharField(blank=True, max_length=15, null=True)),
                ('codigo_ecri', models.CharField(blank=True, max_length=15, null=True)),
                ('responsable', models.TextField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('marca', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('serie', models.TextField(blank=True, null=True)),
                ('clasificacion_misional', models.TextField(blank=True, null=True)),
                ('clasificacion_ips', models.CharField(blank=True, max_length=10, null=True)),
                ('clasificacion_riesgo', models.CharField(blank=True, max_length=10, null=True)),
                ('registro_invima', models.TextField(blank=True, null=True)),
                ('tiempo_vida_util', models.TextField(blank=True, null=True)),
                ('fecha_adquisicion', models.TextField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_fabricacion', models.CharField(blank=True, max_length=20, null=True)),
                ('nit', models.CharField(blank=True, max_length=30, null=True)),
                ('proveedor', models.TextField(blank=True, null=True)),
                ('en_garantia', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_fin_garantia', models.CharField(blank=True, max_length=20, null=True)),
                ('forma_adquisicion', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_documento', models.TextField(blank=True, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=30, null=True)),
                ('hoja_vida', models.CharField(blank=True, max_length=20, null=True)),
                ('registro_importacion', models.TextField(blank=True, null=True)),
                ('manual_operacion', models.CharField(blank=True, max_length=30, null=True)),
                ('manual_mantenimiento', models.TextField(blank=True, null=True)),
                ('guia_rapida', models.CharField(blank=True, max_length=20, null=True)),
                ('instructivo', models.CharField(blank=True, max_length=30, null=True)),
                ('protocolo_mto', models.TextField(blank=True, null=True)),
                ('frecuencia_metrologica', models.CharField(blank=True, max_length=30, null=True)),
                ('mantenimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia_mantenimiento', models.CharField(blank=True, max_length=10, null=True)),
                ('calibracion', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia_calibracion', models.CharField(blank=True, max_length=30, null=True)),
                ('magnitud', models.TextField(blank=True, null=True)),
                ('rango', models.TextField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('rango_trabajo', models.TextField(blank=True, null=True)),
                ('error_maximo', models.TextField(blank=True, null=True)),
                ('voltaje', models.TextField(blank=True, null=True)),
                ('corriente', models.CharField(blank=True, max_length=100, null=True)),
                ('humedad', models.TextField(blank=True, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.TextField(blank=True, null=True)),
                ('otros', models.TextField(blank=True, null=True)),
                ('sede', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('dimensiones', models.TextField(blank=True, null=True)),
                ('valor_compra', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'api_equipo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_usuario',
            },
        ),
        migrations.CreateModel(
            name='TrasladoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_traslado', models.DateField(blank=True, null=True)),
                ('usuario_solicitante', models.CharField(max_length=100)),
                ('sede_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_origen', models.TextField(blank=True, null=True)),
                ('responsable_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('sede_destino', models.CharField(max_length=100)),
                ('ubicacion_destino', models.TextField(blank=True, null=True)),
                ('responsable_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('justificacion', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('ejecutado', 'Ejecutado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('ejecutado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones_ejecucion', models.TextField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('rechazado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
            ],
            options={
                'db_table': 'api_trasladoequipo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='EdicionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('justificacion', models.TextField()),
                ('responsable_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nuevo', models.CharField(blank=True, max_length=100, null=True)),
                ('sede_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('sede_nueva', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio_nuevo', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
            ],
            options={
                'db_table': 'api_edicionequipo',
            },
        ),
        migrations.CreateModel(
            name='DesactivacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desactivacion', models.DateField()),
                ('responsable_desactivacion', models.CharField(max_length=100)),
                ('justificacion', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
            ],
            options={
                'db_table': 'api_desactivacionequipo',
            },
        ),
    ]
