# Generated by Django 4.2 on 2025-12-03 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('responsable_solicitud', models.CharField(max_length=100)),
                ('sede_origen', models.CharField(max_length=100)),
                ('sede_destino', models.CharField(max_length=100)),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('ejecutado', 'Ejecutado')], default='pendiente', max_length=20)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('responsable_aprobacion', models.CharField(blank=True, max_length=100)),
                ('observaciones_aprobacion', models.TextField(blank=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('responsable_ejecucion', models.CharField(blank=True, max_length=100)),
                ('observaciones_ejecucion', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
            ],
            options={
                'db_table': 'api_trasladoequipo',
            },
        ),
    ]
