# Generated by Django 4.2 on 2025-12-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251202_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trasladoequipo',
            options={'ordering': ['-fecha_solicitud']},
        ),
        migrations.RenameField(
            model_name='trasladoequipo',
            old_name='responsable_solicitud',
            new_name='usuario_solicitante',
        ),
        migrations.RemoveField(
            model_name='trasladoequipo',
            name='responsable_aprobacion',
        ),
        migrations.RemoveField(
            model_name='trasladoequipo',
            name='responsable_ejecucion',
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='aprobado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='ejecutado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='fecha_traslado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='rechazado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='responsable_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='responsable_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='ubicacion_destino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trasladoequipo',
            name='ubicacion_origen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trasladoequipo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('ejecutado', 'Ejecutado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='trasladoequipo',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trasladoequipo',
            name='fecha_ejecucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trasladoequipo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trasladoequipo',
            name='observaciones_aprobacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trasladoequipo',
            name='observaciones_ejecucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trasladoequipo',
            name='sede_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
