# Generated by Django 4.2 on 2025-11-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proceso", models.CharField(max_length=200)),
                ("nombre_equipo", models.CharField(max_length=200)),
                ("codigo_inventario", models.CharField(max_length=100)),
                ("codigo_ips", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "codigo_ecri",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubicacion_fisica", models.CharField(max_length=200)),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("serie", models.CharField(max_length=150)),
                (
                    "clasificacion_misional",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "clasificacion_ips",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "clasificacion_riesgo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registro_invima",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("estado", models.CharField(default="activo", max_length=20)),
                ("descripcion_baja", models.TextField(blank=True, null=True)),
                ("fecha_baja", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Responsable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="api.sede",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tiempo_vida_util",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_adquisicion", models.DateField(blank=True, null=True)),
                ("propietario", models.CharField(max_length=100)),
                (
                    "fecha_fabricacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nit", models.CharField(max_length=50)),
                ("proveedor", models.CharField(max_length=200)),
                ("en_garantia", models.BooleanField(default=False)),
                (
                    "fecha_fin_garantia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("forma_adquisicion", models.CharField(max_length=100)),
                ("tipo_documento", models.CharField(max_length=50)),
                ("numero_documento", models.CharField(max_length=100)),
                (
                    "equipo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="api.equipo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetrologiaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("magnitud", models.CharField(max_length=150)),
                ("rango_equipo", models.CharField(max_length=200)),
                ("resolucion", models.CharField(blank=True, max_length=100, null=True)),
                ("rango_trabajo", models.CharField(max_length=200)),
                (
                    "error_maximo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "equipo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrologia_tecnica",
                        to="api.equipo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetrologiaAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mantenimiento", models.BooleanField(default=False)),
                ("frecuencia_mantenimiento", models.IntegerField(default=0)),
                ("calibracion", models.BooleanField(default=False)),
                (
                    "frecuencia_calibracion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "equipo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrologia_admin",
                        to="api.equipo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipo",
            name="responsable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.responsable",
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="sede",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.sede"
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="servicio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.servicio",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hoja_vida", models.BooleanField(default=False)),
                ("registro_importacion", models.BooleanField(default=False)),
                ("manual_operacion", models.BooleanField(default=False)),
                (
                    "manual_mantenimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("guia_rapida", models.BooleanField(default=False)),
                ("instructivo_manejo", models.BooleanField(default=False)),
                ("protocolo_mantenimiento", models.BooleanField(default=False)),
                (
                    "frecuencia_metrologica",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "equipo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="api.equipo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CondicionesFuncionamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voltaje", models.CharField(max_length=50)),
                ("corriente", models.CharField(blank=True, max_length=50, null=True)),
                ("humedad", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "temperatura",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dimensiones", models.CharField(max_length=200)),
                ("peso", models.CharField(max_length=50)),
                ("otros", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "equipo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condiciones",
                        to="api.equipo",
                    ),
                ),
            ],
        ),
    ]
