# Generated by Django 4.2.25 on 2025-11-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sede_nombre_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='nombre_sede',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
