# Generated by Django 4.2.25 on 2025-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sede_nombre_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo_inventario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serie_equipo',
            field=models.CharField(max_length=150),
        ),
    ]
