# Generated by Django 4.2.25 on 2025-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_equipo_codigo_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo_inventario',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serie_equipo',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
